github:
  features:
    # Enable wiki for documentation
    wiki: true
    # Enable issue management
    issues: true
# Web site staging services:
staging:
  profile: ~
  whoami: asf-site

jekyll:
  whoami: master
  target: asf-site

publish:
  whoami: asf-site

notifications:
  commits: commits@eventmesh.apache.org
  issues: commits@eventmesh.apache.org
  pullrequests_status: commits@eventmesh.apache.org
  pullrequests_comment: commits@eventmesh.apache.org
  issues_status: dev@eventmesh.apache.org
  issues_comment: commits@eventmesh.apache.org
  jira_options: link label worklog
